"""Core-only settings. Independent of adapter-side LLM config.

Scope: file paths, HTTP port, bearer token, CORS. No LLM keys — core
never talks to an LLM.
"""

import json
import logging
from pathlib import Path
from typing import Optional
from urllib.parse import urlsplit

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict

logger = logging.getLogger(__name__)

# Default location for the Firebase web-app config JSON (generated by the
# Firebase console). Not a secret: it contains only public project
# identifiers (apiKey, authDomain, projectId, appId, etc.).
_DEFAULT_FIREBASE_CONFIG = Path("website/firebase-config.json")


class CoreConfig(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
        case_sensitive=False,
        populate_by_name=True,
    )

    palio_file_path: Path = Path("data/palio.json")
    palio_games_status_path: Path = Path("data/palio_games_status.json")
    leaderboard_file_path: Path = Path("data/leaderboard.json")
    data_dir: Path = Path("data")

    core_url: str = Field(default="http://localhost:8000", alias="PALIO_CORE_URL")
    bearer_token: Optional[str] = Field(default=None, alias="PALIO_CORE_TOKEN")

    # Cloudflare Turnstile secret for the public borgo poll. Unset =>
    # verification skipped (dev/loopback), like the bearer token.
    turnstile_secret: Optional[str] = Field(default=None, alias="TURNSTILE_SECRET")

    # Operational state for the public popularity poll. Gitignored, NOT
    # part of the FileRegistry / history layer (see core/poll_store.py).
    borgo_poll_path: Path = Path("data/borgo_poll.json")

    @property
    def port(self) -> int:
        parsed = urlsplit(self.core_url)
        if parsed.port is not None:
            return parsed.port
        return 443 if parsed.scheme == "https" else 80

    # Firebase Google sign-in for the manual editor.
    #
    # Path to the Firebase web-app config JSON (downloaded from the Firebase
    # console). If the file exists, it populates all firebase_* fields below.
    # Env vars still win if both are set.
    firebase_config_path: Path = Field(
        default=_DEFAULT_FIREBASE_CONFIG, alias="FIREBASE_CONFIG_PATH"
    )
    firebase_project_id: Optional[str] = Field(
        default=None, alias="FIREBASE_PROJECT_ID"
    )
    firebase_api_key: Optional[str] = Field(default=None, alias="FIREBASE_API_KEY")
    firebase_auth_domain: Optional[str] = Field(
        default=None, alias="FIREBASE_AUTH_DOMAIN"
    )
    firebase_app_id: Optional[str] = Field(default=None, alias="FIREBASE_APP_ID")
    editor_allowed_emails: Optional[str] = Field(
        default=None, alias="EDITOR_ALLOWED_EMAILS"
    )

    def model_post_init(self, __context) -> None:
        """Backfill firebase_* fields from the web-config JSON if present."""
        path = self.firebase_config_path
        if not path or not path.is_file():
            return
        try:
            data = json.loads(path.read_text(encoding="utf-8"))
        except Exception as exc:
            logger.warning("could not read %s: %s", path, exc)
            return
        if not self.firebase_project_id:
            self.firebase_project_id = data.get("projectId")
        if not self.firebase_api_key:
            self.firebase_api_key = data.get("apiKey")
        if not self.firebase_auth_domain:
            self.firebase_auth_domain = data.get("authDomain")
        if not self.firebase_app_id:
            self.firebase_app_id = data.get("appId")

    cors_allowed_origins: Optional[str] = Field(
        default=None, alias="CORS_ALLOWED_ORIGINS"
    )

    def allowed_emails_set(self) -> set[str]:
        if not self.editor_allowed_emails:
            return set()
        return {
            e.strip().lower()
            for e in self.editor_allowed_emails.split(",")
            if e.strip()
        }

    def allowed_origins_list(self) -> list[str]:
        if self.cors_allowed_origins:
            return [o.strip() for o in self.cors_allowed_origins.split(",") if o.strip()]
        return [
            "http://localhost:3000",
            "http://127.0.0.1:3000",
            "http://localhost:3010",
            "http://127.0.0.1:3010",
            "http://localhost:5173",
            "http://127.0.0.1:5173",
        ]
